#include<iostream.h>
#include<conio.h>
void main()
{
	int a,b;
	clrscr();

	cout<<"Enter the Value of Number a :: ";
	cin>>a;

	cout<<"Enter the Value of Number b :: ";
	cin>>b;

	cout<<"Addtition of given two Number is            :: "<<a+b<<endl;

	cout<<"SUbstraction of given two Number is         :: "<<a-b<<endl;

	cout<<"Multiplication of given two Number is       :: "<<a*b<<endl;

	cout<<"Division of given two Number is             :: "<<(float)a/b<<endl;

	cout<<"Modulo of given two Number is               :: "<<a%b<<endl;


	getch();


}

